name = "astrology-analysis"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

# KV Namespace binding
# Replace XXXXX with actual ID from `wrangler kv:namespace create SESSION`
# [[kv_namespaces]]
# binding = "SESSION"
# id = "XXXXX"

# Environment variables
[vars]
# Add your variables here

# [[env.production.kv_namespaces]]
# binding = "SESSION"
# id = "XXXXX"

[site]
bucket = "./dist" 